description: Generate docker images with custom packages
name: stack-docker
display-name: stack-docker
picture: stack.png
category: SRE
compatibility:
  - Docker
technologies:
  - Docker
about: README.md
