description: Generate docker images with custom packages
name: stack-docker
display-name: stack-docker
picture: stack.png
category: Backend
compatibility:
  - linux
  - macos
technologies:
  - Docker
about: docs/about.md
use-cases:
  - title: Use Case Title
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml