description: Generate docker images with custom packages
name: stack-docker
display-name: stack-docker
picture: stack.png
category: SRE
compatibility: # Put a list of technologies compatible with the stack
  - Java
technologies:
  - Docker
about: README.md
use-cases:
  - title: Stack Docker
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml