name: docker-build
description: Build all Dockerfiles
supported-os:
- linux
- mac
inputs:
  - label: Tag Image
    type: text
    name: tag_image
    default: latest
  - label: Use Cache
    type: bool
    name: caching
    default: true
requirements-check:
  docker:
    check-command: docker --version
    info: Please install docker before run this task!
command: |
  #!/bin/bash

  set -e

  BASE_FOLDER="$(pwd)"

  PROJECTS="$(find ${BASE_FOLDER} -iname Dockerfile -exec dirname {} \;)"

  for i in $PROJECTS; do
    cd "$i"
    echo ""
    echo "***** DOCKER BUILD: {{ docker_repository }}{{ project_name }}/${PWD##*/} *****"
    docker build \
      {% if not caching %} --force-rm --no-cache --pull {% endif %}
      -t "{{ docker_repository }}/{{ project_name }}/${PWD##*/}:{{ tag_image }}" .
  done
