name: create-image
description: Create custom docker image
display-name: create-image
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Base Image
    type: text
    name: base_image
    default: alpine
  - label: Tag Image
    type: text
    name: tag_image
    default: latest
  - label: Package Manager
    name: package_manager
    type: text
    items:
      - apk
      - apt-get
      - rpm
  - label: Package names, seprated by spaces
    type: text
    name: packages
    default: curl

computed-inputs:
  folder_name: "{{ base_image | to_kebab }}-{{ packages | to_kebab }}"
