name: create-dockerfile
description: Create custom Dockerfile
display-name: create-dockerfile
picture: plugin.png
category: SRE # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - Docker
about: README.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - Docker
types:
  - app
inputs:
  # Docker
  - label: Docker Base Image
    type: text
    name: base_image
    default: alpine
  - label: Docker Image Tag
    type: text
    name: tag_image
    default: latest
  
  # System Packages
  - label: Install System Packages
    type: bool
    name: install_system_packages
    default: true
  - label: Package Manager
    name: package_manager
    type: text
    items:
      - apk
      - apt-get
      - yum
    condition:
      variable: install_system_packages
      operator: ==
      value: true
  - label: Package Names (seprated by spaces)
    type: text
    name: packages
    default: curl
    condition:
      variable: install_system_packages
      operator: ==
      value: true
    
  # Language Packages
  - label: Install Code Packages
    type: bool
    name: install_code_packages
    default: false
  - label: Code Package Manager
    name: code_package_manager
    type: text
    items:
      - pip
      - npm
    condition:
      variable: install_code_packages
      operator: ==
      value: true
  - label: Code Package Names (seprated by spaces)
    type: text
    name: code_packages
    default: pyyaml
    condition:
      variable: install_code_packages
      operator: ==
      value: true

computed-inputs:
  folder_name: >-
    {{- base_image | to_kebab -}}-{{- tag_image | replace('.', '-') | to_kebab -}}

    {%- if install_system_packages -%}
    -{{- packages.split(' ') | sort | join(' ') | to_kebab -}}
    {%- endif -%}

    {%- if install_code_packages -%}
    -{{- code_package_manager -}}-
    {{- code_packages.split(' ') | sort | join(' ') | to_kebab -}}
    {%- endif -%}
